USE [DAW]
GO

/****** Object:  Table [dbo].[ARTICULOS]    Script Date: 13/05/2022 14:59:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ARTICULOS](
	[ID_ARTICULO] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPCION] [varchar](50) NULL,
	[FABRICANTE] [varchar](50) NULL,
	[PESO] [int] NULL,
	[ALTO] [int] NULL,
	[LARGO] [int] NULL,
	[ANCHO] [int] NULL,
	[PRECIO] [decimal](10, 2) NULL,
	[N_REGISTRO] [varchar](50) NULL,
 CONSTRAINT [PK_ARTICULOS] PRIMARY KEY CLUSTERED 
(
	[ID_ARTICULO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

