USE [master]
GO

/****** Object:  Database [DAW]    Script Date: 17/05/2022 14:12:11 ******/
CREATE DATABASE [DAW]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DAW', FILENAME = N'E:\MSSQL\Data\DAW\DAW.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DAW_log', FILENAME = N'E:\MSSQL\Data\DAW\DAW_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DAW].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DAW] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DAW] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DAW] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DAW] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DAW] SET ARITHABORT OFF 
GO

ALTER DATABASE [DAW] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DAW] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DAW] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DAW] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DAW] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DAW] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DAW] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DAW] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DAW] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DAW] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DAW] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DAW] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DAW] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DAW] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DAW] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DAW] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DAW] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DAW] SET RECOVERY FULL 
GO

ALTER DATABASE [DAW] SET  MULTI_USER 
GO

ALTER DATABASE [DAW] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DAW] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DAW] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DAW] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DAW] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DAW] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DAW] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DAW] SET  READ_WRITE 
GO

