USE [DAW]
GO

/****** Object:  StoredProcedure [dbo].[PA_BORRAR_USUARIO]    Script Date: 09/06/2022 16:31:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[PA_BORRAR_USUARIO]  
( 
@ID_USUARIO INT,  

 @MENSAJE VARCHAR(2000) OUTPUT,  
 @RETCODE INT OUTPUT  
)  
AS   
BEGIN TRY   
		
 SET @RETCODE = 0
 SET @MENSAJE = ''

 IF ISNULL (@ID_USUARIO, 0) <= 0  
  
 BEGIN  
  SET @MENSAJE = 'ID NO VÁLIDO'  
  SET @RETCODE = 1  
  RETURN  
 END  

 IF EXISTS (SELECT * FROM USUARIOS WHERE ID_USUARIO = @ID_USUARIO)  
 BEGIN  
  DELETE USUARIOS   
  WHERE ID_USUARIO = @ID_USUARIO  
  SET @MENSAJE = 'Usuario borrado correctamente'
 END  

  
END TRY  
  
BEGIN CATCH  
 SET @MENSAJE = ERROR_MESSAGE()
 SET @RETCODE = -1
END CATCH  
GO

