USE [DAW]
GO

/****** Object:  StoredProcedure [dbo].[PA_BORRAR_PEDIDO_ARTICULO]    Script Date: 17/06/2022 11:09:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[PA_BORRAR_PEDIDO_ARTICULO]  
( 
@ID_PEDIDO_ARTICULO INT,  

 @MENSAJE VARCHAR(2000) OUTPUT,  
 @RETCODE INT OUTPUT  
)  
AS   
BEGIN TRY   
		
 SET @RETCODE = 0
 SET @MENSAJE = ''

 IF ISNULL (@ID_PEDIDO_ARTICULO, 0) <= 0  
  
 BEGIN  
  SET @MENSAJE = 'ID NO VÁLIDO'  
  SET @RETCODE = 1  
  RETURN  
 END  

 IF EXISTS (SELECT * FROM PEDIDOS_ARTICULOS WHERE ID_PEDIDO_ARTICULO = @ID_PEDIDO_ARTICULO)  
 BEGIN  
  DELETE PEDIDOS_ARTICULOS   
  WHERE ID_PEDIDO_ARTICULO = @ID_PEDIDO_ARTICULO  
 END  

  SET @MENSAJE = 'Pedido Articulo borrado correctamente'
  
END TRY  
  
BEGIN CATCH  
 SET @MENSAJE = ERROR_MESSAGE()
 SET @RETCODE = -1
END CATCH  
GO

