USE [DAW]
GO

/****** Object:  StoredProcedure [dbo].[PA_LOGIN]    Script Date: 17/05/2022 14:13:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[PA_LOGIN]
(  
	@EMAIL VARCHAR(100),
	@USER VARCHAR(100),
	@PASS VARCHAR(100),

  
 @MENSAJE VARCHAR(100) OUTPUT,  
 @RETCODE INT OUTPUT  
)  
AS  
  
BEGIN TRY  
   

   SET @RETCODE = 0
   SET @MENSAJE = ''
   
 IF ISNULL(@EMAIL,'') = ''  
 BEGIN  
  SET  @RETCODE = 10  
  SET @MENSAJE = 'El parametro email no puede ser vacío'  
  RETURN  
 END  
IF EXISTS( SELECT USUARIO FROM USUARIOS WHERE USUARIO = @USER )	
IF EXISTS( SELECT EMAIL FROM USUARIOS WHERE EMAIL =  @EMAIL)
IF EXISTS( SELECT PASS FROM USUARIOS WHERE PASS = @PASS)
	BEGIN
		SET @RETCODE = 0
		SET @MENSAJE = 'Credenciales correctos'
		RETURN
	END


SET @RETCODE = 1
SET @MENSAJE = 'Credenciales incorrectos'
END TRY  

BEGIN CATCH  
END CATCH
GO

