USE [DAW]
GO

/****** Object:  Table [dbo].[PEDIDOS_ARTICULOS]    Script Date: 17/06/2022 11:08:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PEDIDOS_ARTICULOS](
	[ID_PEDIDO_ARTICULO] [int] IDENTITY(1,1) NOT NULL,
	[ID_ARTICULO] [int] NULL,
	[DESCRIPCION] [varchar](50) NULL,
	[TALLA] [char](1) NULL,
	[COLOR] [varchar](50) NULL,
	[CANTIDAD] [int] NULL,
	[PRECIO_UNIDAD] [decimal](10, 2) NULL,
	[PRECIO] [decimal](10, 2) NULL,
 CONSTRAINT [PK_PEDIDOS_ARTICULOS] PRIMARY KEY CLUSTERED 
(
	[ID_PEDIDO_ARTICULO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PEDIDOS_ARTICULOS]  WITH CHECK ADD  CONSTRAINT [FK__PEDIDOS_A__ID_AR__40F9A68C] FOREIGN KEY([ID_ARTICULO])
REFERENCES [dbo].[ARTICULOS] ([ID_ARTICULO])
GO

ALTER TABLE [dbo].[PEDIDOS_ARTICULOS] CHECK CONSTRAINT [FK__PEDIDOS_A__ID_AR__40F9A68C]
GO

