USE [DAW]
GO

/****** Object:  Table [dbo].[STOCK]    Script Date: 27/05/2022 14:58:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[STOCK](
	[ID_ARTICULO] [int] NOT NULL,
	[CANTIDAD_STOCK] [int] NULL,
	[CANTIDAD_PEDIDO] [int] NULL,
	[CANTIDAD_ENVIO] [int] NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[STOCK]  WITH CHECK ADD  CONSTRAINT [FK__STOCK__ID_ARTICU__40058253] FOREIGN KEY([ID_ARTICULO])
REFERENCES [dbo].[ARTICULOS] ([ID_ARTICULO])
GO

ALTER TABLE [dbo].[STOCK] CHECK CONSTRAINT [FK__STOCK__ID_ARTICU__40058253]
GO

ALTER TABLE [dbo].[STOCK]  WITH CHECK ADD  CONSTRAINT [FK_STOCK_ARTICULOS] FOREIGN KEY([ID_ARTICULO])
REFERENCES [dbo].[ARTICULOS] ([ID_ARTICULO])
GO

ALTER TABLE [dbo].[STOCK] CHECK CONSTRAINT [FK_STOCK_ARTICULOS]
GO

