USE [DAW]
GO

/****** Object:  View [dbo].[V_STOCK]    Script Date: 10/06/2022 14:44:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[V_STOCK]    AS    SELECT DBO.ARTICULOS.ID_ARTICULO, ARTICULOS.DESCRIPCION, dbo.ROPA.COLOR, dbo.ROPA.TALLA, dbo.STOCK.CANTIDAD_STOCK, dbo.STOCK.CANTIDAD_PEDIDO, dbo.STOCK.CANTIDAD_ENVIO
FROM            dbo.ARTICULOS left JOIN
                         dbo.ROPA ON dbo.ARTICULOS.ID_ARTICULO = dbo.ROPA.ID_ARTICULO left JOIN
                         dbo.STOCK ON dbo.ARTICULOS.ID_ARTICULO = dbo.STOCK.ID_ARTICULO AND dbo.ARTICULOS.ID_ARTICULO = dbo.STOCK.ID_ARTICULO
GO

